<?php

return [

    /*
    |--------------------------------------------------------------------------
    | STATIC STRINGS TRANSLATIONS
    |--------------------------------------------------------------------------
    |
    |  !!! WARNING - This is a file generated by the LanguagesService. !!!
    |  You should not modify it, as it shall be replaced next time this service is executed.
    |
    */

    "apply_now" => "Подать заявку сейчас",
    "new_jobs" => "Новые вакансии"


];


