<?php

return [

    /*
    |--------------------------------------------------------------------------
    | STATIC STRINGS TRANSLATIONS
    |--------------------------------------------------------------------------
    |
    |  !!! WARNING - This is a file generated by the LanguagesService. !!!
    |  You should not modify it, as it shall be replaced next time this service is executed.
    |
    */

    "hello" => "Hello",
    "email_confirm_p" => "Please confirm your email by clicking the button below.",
    "email_confirm" => "Confirm Email",
    "regards" => "Regards",
    "team" => "Team",
    "reset_p1" => "You received this email because we received a password reset request for your account.",
    "reset_p2" => "To reset your password, please click on the button below:",
    "reset_pass" => "Reset password",
    "reset_p3" => "If you have not requested a password reset, ignore this email.",

];


