<?php

return [

    /*
    |--------------------------------------------------------------------------
    | STATIC STRINGS TRANSLATIONS
    |--------------------------------------------------------------------------
    |
    |  !!! WARNING - This is a file generated by the LanguagesService. !!!
    |  You should not modify it, as it shall be replaced next time this service is executed.
    |
    */

    'hello' => 'Здравствуйте',
    'email_confirm_p' => 'Пожалуйста, подтвердите ваш email, нажав на кнопку ниже.',
    'email_confirm' => 'Подтвердить Email',
    'regards' => 'С уважением',
    'command' => 'Команда',
    'reset_p1' => 'Вы получили это письмо, потому что мы получили запрос на сброс пароля для вашей учетной записи.'
    'reset_p2' => 'Чтобы сбросить пароль, пожалуйста, нажмите на кнопку ниже:'

];


