<?php

return [

  /*
  |--------------------------------------------------------------------------
  | STATIC STRINGS TRANSLATIONS
  |--------------------------------------------------------------------------
  |
  |  !!! WARNING - This is a file generated by the LanguagesService. !!!
  |  You should not modify it, as it shall be replaced next time this service is executed.
  |
   */

  'accepted' => ':attribute պետք է ընդունվի։',
  'accepted_if' => ':attribute պետք է ընդունվի, երբ :other :value է:',
  'active_url' => ':attribute վավեր URL չէ:',
  'after' => ':attribute պետք է լինի :date -ից հետո ամսաթիվ:',
  'alpha' => ':attribute պետք է պարունակի միայն տառեր:',
  'alpha_dash' => ':attribute պետք է պարունակի միայն տառեր, թվեր, գծիկներ և ընդգծումներ:',
  'alpha_num' => ':attribute պետք է պարունակի միայն տառեր և թվեր:',
  'array' => ':attribute պետք է լինի զանգված:',
  'ascii' => ':attribute պետք է պարունակի միայն մեկ բայթանոց ալֆան-թվային նիշեր և նշաններ:',
  'before' => ':attribute պետք է լինի :date -ից առաջ ամսաթիվ:',
  'before_or_equal' => ':attribute պետք է լինի :date -ին նախորդող կամ հավասար ամսաթիվ:',
  'after_or_equal' => ':attribute պետք է լինի :date -ին հաջորդող կամ հավասար ամսաթիվ:',
  'date_format' => ':attribute ձևաչափն անվավեր է:',
  'between' => [
    'array' => ':attribute պետք է ունենա :min և :max տարրերի միջև:',
    'file' => ':attribute պետք է լինի :min և :max կիլոբայթների միջև:',
    'numeric' => ':attribute պետք է լինի :min -ի և :max -ի միջև:',
    'string' => ':attribute պետք է լինի :min և :max նիշերի միջև:',
  ],
  'boolean' => ':attribute դաշտը պետք է լինի true կամ false:',
  'confirmed' => ':attribute հաստատումը չի համընկնում:',
  'current_password' => 'Գաղտնաբառը սխալ է:',
  'date' => ':attribute վավեր ամսաթիվ չէ:',
  'date_equals' => ':attribute պետք է լինի :date -ին հավասար ամսաթիվ:',
  'decimal' => ':attribute պետք է ունենա :decimal տասնորդական թվեր:',
  'declined' => ':attribute պետք է մերժվի:',
  'declined_if' => ':attribute պետք է մերժվի, երբ :other -ը :value է:',
  'different' => ':attribute -ը և :other -ը պետք է տարբեր լինեն։',
  'digits' => ':attribute պետք է լինի :digits թվանշան:',
  'digits_between' => ':attribute պետք է լինի :min և :max թվանշանների միջև:',
  // 'dimensions' => ':հատկանիշն ունի պատկերի անվավեր չափեր:',
  'dimensions' => [
    'min_width' => ':min',
    'max_width' => ':max',
    'min_height' => ':min',
    'max_height' => ':max',
  ],
  'distinct' => ':attribute դաշտը կրկնօրինակված արժեք ունի:',
  'doesnt_end_with' => ':attribute չի կարող ավարտվել հետևյալներից որևէ մեկով. :values',
  'doesnt_start_with' => ':attribute չի կարող սկսվել հետևյալներից որևէ մեկով. :values',
  'email' => ':attribute պետք է վավեր էլփոստի հասցե լինի:',
  'ends_with' => ':attribute պետք է ավարտվի հետևյալներից մեկով. :values',
  'enum' => 'Ընտրված :հատկանիշն անվավեր է:',
  'exists' => 'Ընտրված :հատկանիշն անվավեր է:',
  'file' => ':attribute պետք է լինի ֆայլ:',
  'filled' => ':attribute դաշտը պետք է արժեք ունենա:',
  'gt' => [
    'array' => ':attribute պետք է ունենա ավելի քան :value տարրեր:',
    'file' => ':attribute պետք է լինի :value կիլոբայթից մեծ:',
    'numeric' => ':attribute պետք է լինի :value -ից մեծ:',
    'string' => ':attribute պետք է մեծ լինի :value նիշերից:',
  ],
  'gte' => [
    'array' => ':attribute պետք է ունենա :value տարրեր կամ ավելին:',
    'file' => ':attribute պետք է մեծ կամ հավասար լինի :value կիլոբայթին:',
    'numeric' => ':attribute պետք է մեծ կամ հավասար լինի :value -ին:',
    'string' => ':attribute պետք է մեծ կամ հավասար լինի :value նիշերին:',
  ],
  'image' => ':attribute պետք է լինի պատկեր:',
  'in' => 'Ընտրված :attribute անվավեր է:',
  'in_array' => ':attribute դաշտը գոյություն չունի :other -ում:',
  'integer' => ':attribute պետք է լինի ամբողջ թիվ։',
  'ip' => ':attribute պետք է լինի վավեր IP հասցե:',
  'ipv4' => ':attribute պետք է լինի վավեր IPv4 հասցե:',
  'ipv6' => ':attribute պետք է լինի վավեր IPv6 հասցե:',
  'json' => ':attribute պետք է լինի վավեր JSON տող:',
  'lowercase' => ':attribute պետք է լինի փոքրատառ:',
  'lt' => [
    'array' => ':attribute պետք է ունենա :value -ից պակաս տարրեր.',
    'file' => ':attribute պետք է լինի :value կիլոբայթից փոքր.',
    'numeric' => ':attribute պետք է լինի :value -ից փոքր։',
    'string' => ':attribute պետք է լինի փոքր :value նիշերից.',
  ],
  'lte' => [
    'array' => ':attribute չպետք է ունենա ավելի քան :value տարրեր։',
    'file' => ':attribute պետք է լինի :value կիլոբայթից փոքր կամ հավասար:',
    'numeric' => ':attribute պետք է լինի փոքր կամ հավասար :value -ին:',
    'string' => ':attribute պետք է լինի փոքր կամ հավասար :value նիշերին:',
  ],
  'mac_address' => ':attribute պետք է լինի վավեր MAC հասցե:',
  'max' => [
    'array' => ':attribute չպետք է ունենա ավելի քան :max տարրեր:',
    'file' => ':attribute չպետք է լինի :max կիլոբայթից մեծ:',
    'numeric' => ':attribute չպետք է լինի :max -ից մեծ:',
    'string' => ':attribute չպետք է լինի :max նիշից մեծ:',
  ],
  'max_digits' => ':attribute չպետք է ունենա ավելի քան :max թվանշան:',
  'mimes' => ':attribute պետք է լինի :values ​​տեսակի ֆայլ:',
  'mimetypes' => ':attribute պետք է լինի :values ​​տեսակի ֆայլ:',
  'min' => [
    'array' => ':attribute պետք է ունենա առնվազն :min տարրեր.',
    'file' => ':attribute պետք է լինի առնվազն :min կիլոբայթ.',
    'numeric' => ':attribute պետք է լինի առնվազն :min.',
    'string' => ':attribute պետք է լինի առնվազն :min նիշ.',
  ],
  'min_digits' => ':attribute պետք է ունենա առնվազն :min թվանշաններ:',
  'missing' => ':attribute դաշտը պետք է բացակայի:',
  'missing_if' => ':attribute դաշտը պետք է բացակայի, երբ :other -ը :value է:',
  'missing_unless' => ':attribute դաշտը պետք է բացակայի, եթե :other -ը :value չէ:',
  'missing_with' => ':attribute դաշտը պետք է բացակայի, երբ առկա է :values:',
  'missing_with_all' => ':attribute դաշտը պետք է բացակայի, երբ առկա են :values:',
  'multiple_of' => ':attribute պետք է լինի :value -ի բազմապատիկ:',
  'not_in' => 'Ընտրված :հատկանիշն անվավեր է:',
  'not_regex' => ':attribute ձևաչափն անվավեր է:',
  'numeric' => ':attribute պետք է լինի թիվ։',
  'password' => [
    'letters' => ':attribute պետք է պարունակի առնվազն մեկ տառ:',
    'mixed' => ':attribute պետք է պարունակի առնվազն մեկ մեծատառ և մեկ փոքրատառ:',
    'numbers' => ':attribute պետք է պարունակի առնվազն մեկ թիվ։',
    'symbols' => ':attribute պետք է պարունակի առնվազն մեկ նշան:',
    'uncompromised' => 'Տվյալ :attribute հայտնվել է տվյալների արտահոսքի մեջ: Խնդրում ենք ընտրել այլ :attribute :',
  ],
  'present' => ':attribute դաշտը պետք է լինի:',
  'prohibited' => ':attribute դաշտն արգելված է:',
  'prohibited_if' => ':attribute դաշտն արգելված է, երբ :other -ը :value է:',
  'prohibited_unless' => ':attribute դաշտն արգելված է, եթե :other-ը :values -ում չէ:',
  'prohibits' => ':attribute դաշտն արգելում է :other -ին ներկա լինել:',
  'regex' => ':attribute ձևաչափն անվավեր է:',
  'required' => ':attribute դաշտը պարտադիր է:',
  'required_array_keys' => ':attribute դաշտը պետք է պարունակի գրառումներ՝ :values -ի համար:',
  'required_if' => ':attribute դաշտը պարտադիր է, երբ :other-ը :value է:',
  'required_if_accepted' => ':attribute դաշտը պարտադիր է, երբ :other ընդունված է:',
  'required_unless' => ':attribute դաշտը պարտադիր է, եթե :other -ը :values-ում չէ:',
  'required_with' => ':attribute դաշտը պահանջվում է, երբ առկա է :values:',
  'required_with_all' => ':attribute դաշտը պահանջվում է, երբ առկա են :values:',
  're_uired_without' => ':attribute դաշտը պահանջվում է, երբ :values ​​չկա:',
  'required_without' => ' :attribute դաշտը պարտադիր է, երբ :values չկա:',
  'required_without_all' => ':attribute դաշտը պարտադիր է, երբ :value -ներից ոչ մեկը չկա:',
  'same' => ':attribute -ը և :other -ը պետք է համապատասխանեն:',
  'size' => [
    'array' => ':attribute պետք է պարունակի :size տարրեր:',
    'file' => ':attribute պետք է լինի :size կիլոբայթ:',
    'numeric' => ':attribute պետք է լինի :size :',
    'string' => ':attribute պետք է լինի :size նիշ:',
  ],
  'starts_with' => ':attribute պետք է սկսվի հետևյալներից մեկով. :values :',
  'string' => ':attribute պետք է լինի տող:',
  'timezone' => ':attribute պետք է վավեր ժամային գոտի լինի:',
  'unique' => ':attribute արդեն գոյություն ունի։',
  'uploaded' => 'Չհաջողվեց վերբեռնել :attribute :',
  'uppercase' => ':attribute պետք է լինի մեծատառ:',
  'url' => ':attribute պետք է լինի վավեր URL:',
  'ulid' => ':attribute պետք է լինի վավեր ULID:',
  'uuid' => ':attribute պետք է լինի վավեր UUID:',
  'custom' => '',
  'attributes' => '',
  'empty_field' => 'Լրացնել առնվազն մեկ դաշտ',
  'result_not_found' => 'Արդյունք չի գտնվել',
  'empty_seria_number' => 'Համար կամ սերիա դաշտը դատարկ է',
  'there_is_a_limit' => 'Առկա է սահմանափակում',
  'notfound' => 'Արդյունք չի գտնվել',
  'language' => 'Լեզու',
  'email_or_password_is_incorrect' => 'էլ. փոստը կամ գաղտնաբառը սխալ է',
  'generated_fail' => 'գեներացված համարանիշ չկա',
  'Vehicle_has_not_been_registered' => 'տվյալ Տրանսպորտային Միջոցը հաշվառում չի անցել',
  'you_dont_have_permition' => 'Դուք չունեք համապատասխան թույլտվություն մուտք գործելու համար',


  /*
  |--------------------------------------------------------------------------
  | Custom Validation Language Lines
  |--------------------------------------------------------------------------
  |
  | Here you may specify custom validation messages for attributes using the
  | convention "attribute.rule" to name the lines. This makes it quick to
  | specify a specific custom language line for a given attribute rule.
  |
   */

  'custom' => [
        'agree_terms' => [
            'accepted' => 'Ընդունեք Պայմանները և դրույթները',
        ],
        'current_password' => [
            'current_password' => ':attribute դաշտը սխալ է'
        ]

  ],

  /*
  |--------------------------------------------------------------------------
  | Custom Validation Attributes
  |--------------------------------------------------------------------------
  |
  | The following language lines are used to swap our attribute placeholder
  | with something more reader friendly such as "E-Mail Address" instead
  | of "email". This simply helps us make our message more expressive.
  |
   */

    'attributes' => [
        'name' => 'Անուն',
        'surname' => 'Ազգանուն',
        'email' => 'Էլ․ հասցե',
        'password' => 'գաղտնաբառ',
        'confirm_password' => 'Կրկնել գաղտնաբառ',
        'current_password' => 'Ընթացիկ գաղտնաբառ',
        'phone' => 'Հեռախոս',
        'roles' => 'Դերեր',
        'status' => 'Կարգավիճակ',
        'quantity'=> "Քանակ",
        'price'=> "Գին",
        'translate.*.description' => 'Նկարագրություն',
        'translate.*.name' => 'Վերնագիր',
        'max_quantity' => 'Առավելագույն քանակ',
        'min_quantity' => 'Նվազագույն քանակ',
        'time' => 'Ժամ',
        'date' => 'Օր',
        'price_am' => 'Գին',
        'price_other' => 'Գին',
        'title' => 'Առաջադրանքի անվանում',
        'location_id' => "Մարզ",
        'category_id'=> "Կատեգորիա",
        'sub_category_id'=>"Ենթակատեգորիա",
        'price_min'=> "Նվազագույն գին",
        'price_max'=> "Առավելագույն գին",
        'start_date' => "Մեկնարկի ամսաթիվ",
        'end_date' => "Ավարտի ամսաթիվ",
        'agree_terms' => 'Պայմանները և դրույթները',
        'description' => 'Բովանդակություն',
        'mark' => 'Գնահատական'

    ]

];
